name: Run Python Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Run Python Program
        run: python hello.py
